### ISSUE TITLE
XSFP will not install via pip.

### ISSUE THREAD

**Issue by tcarroll2** [dem214/xspf-lib#1]
**Describe the bug**
pip install xspf-lib does not work.
**To Reproduce**
1. pip install xspf-lib

**Expected behavior**
for xsfp to be installed
**Screenshots**
<img width="572" alt="Screen Shot 2020-08-25 at 11 59 13 AM" src="https://user-images.githubusercontent.com/32363030/91205002-7b061580-e6ca-11ea-9efb-df6f9093ce5a.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 15.6
 - Python Version: 3.7.4
 - Environment: Visual Studio Code v1.48.0

**Additional context**
I do not know what has changed.  I am using libpytunes in my python program and there is a call to import this library within libpytunes and all of a sudden it has stopped working.  So, I tried to install the library via pip and it will not install.

**Comment by dem214** [comment]
Please, check spelling. XS**PF**, pronouncing as "spiff", not XS**FP**. 
However, I didn't find any mention of this package in source code of [libpytunes](https://github.com/liamks/libpytunes). You can double check the source code of libpytunes (there are can be import of package with the almost same name), or, maybe, contact with contributors.
